baseURL = "https://example.com/"
languageCode = "en-us"
title = "Tinkerface"
theme = "rocinante"
paginate = 3

[markup]
  [markup.highlight]
    # https://xyproto.github.io/splash/docs/all.html
    # style = "monokai"
    style = "arduino"
    # style = "fruity"
  [markup.goldmark.renderer]
    unsafe= true

[params]
  favicon = "/icons/favicon.png"
  mainSections = ["projects", "infos", "post"]
#   email = "mail@example.com"
  about = """
About section. Enter details about you here.
"""

  [[params.links]]
    # [[params.links.link]]
    #   name = "Resume"
    #   href = "/Resume.pdf"
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      smart_email_link = true

  [[params.links]]
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/CouldBeThis"
      new_tab = true
    # [[params.links.link]]
    #   name = "Mastodon"
    #   href = "https://mastodon.social/"
    #   new_tab = true
    # [[params.links.link]]
    #   name = "Twitter"
    #   href = "https://twitter.com/"
    #   new_tab = true
    # [[params.links.link]]
    #   name = "Instagram"
    #   href = "https://instagram.com/"
    #   new_tab = true